"""
Builds cybertrace.db (SQLite) from the synthetic CSVs generated by
ml/generate_dataset.py. Run after generate_dataset.py, before starting the API.
"""
import os
import sqlite3
import pandas as pd

BASE = os.path.join(os.path.dirname(__file__), "..", "..")
DATA_DIR = os.path.join(BASE, "data")
DB_PATH = os.path.join(DATA_DIR, "cybertrace.db")


def build_db():
    conn = sqlite3.connect(DB_PATH)

    tables = {
        "locations": "locations.csv",
        "accounts": "accounts.csv",
        "complaints": "complaints.csv",
        "transactions": "transactions.csv",
        "withdrawals": "withdrawals.csv",
    }
    for table, csv_file in tables.items():
        path = os.path.join(DATA_DIR, csv_file)
        df = pd.read_csv(path)
        df.to_sql(table, conn, if_exists="replace", index=False)
        print(f"Loaded {len(df)} rows into '{table}'")

    # predictions & alerts tables are populated at runtime by the API
    conn.execute("""
        CREATE TABLE IF NOT EXISTS predictions (
            prediction_id TEXT PRIMARY KEY,
            complaint_id TEXT,
            account_id TEXT,
            created_at TEXT,
            risk_level TEXT,
            top_locations_json TEXT,
            explanation_json TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS alerts (
            alert_id TEXT PRIMARY KEY,
            alert_type TEXT,
            location_id TEXT,
            complaint_id TEXT,
            probability REAL,
            amount REAL,
            risk_level TEXT,
            created_at TEXT,
            status TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS notification_log (
            notification_id TEXT PRIMARY KEY,
            alert_id TEXT,
            channel TEXT,
            recipient TEXT,
            sent_at TEXT,
            status TEXT
        )
    """)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS investigation_notes (
            note_id TEXT PRIMARY KEY,
            complaint_id TEXT,
            author TEXT,
            category TEXT,
            content TEXT,
            created_at TEXT
        )
    """)
    conn.commit()
    conn.close()
    print(f"\nDatabase built at {DB_PATH}")


if __name__ == "__main__":
    build_db()
